name: Feature Request
description: Suggest an enhancement for Minidoro
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
        Please include the ⚡ emoji at the start of your title if you've read our contributing guidelines.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem would this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What solution would you like to see?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
    validations:
      required: false